version: "3"

networks:
  marvel:

services:
  marvel-server:

    image: nginx:stable-alpine
    container_name: marvel-server
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
    depends_on:
      - marvelapp    
    volumes:
     - ./:/var/www
     - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - marvel
       
  marvelapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: sujith/laravel  
    container_name: marvelapp
    volumes:
      - ./:/var/www
    ports:
      - "9001:9000"
    networks:
      - marvel           